"""empty message

Revision ID: 3e5ec0f87408
Revises: 6544788b0c14
Create Date: 2023-06-20 16:35:34.615168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e5ec0f87408'
down_revision = '6544788b0c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_loan_ticket',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('time_lend', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['patron_id'], ['patron.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'patron_id')
    )
    op.drop_table('book_lend')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_lend',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patron_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_lend', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('return_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='book_lend_book_id_fkey'),
    sa.ForeignKeyConstraint(['patron_id'], ['patron.id'], name='book_lend_patron_id_fkey'),
    sa.PrimaryKeyConstraint('book_id', 'patron_id', name='book_lend_pkey')
    )
    op.drop_table('book_loan_ticket')
    # ### end Alembic commands ###
