"""empty message

Revision ID: 5e8be65fbce9
Revises: 326324af66fa
Create Date: 2023-06-21 09:19:15.932730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8be65fbce9'
down_revision = '326324af66fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_loan_ticket', sa.Column('status', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_loan_ticket', 'status')
    # ### end Alembic commands ###
