"""empty message

Revision ID: 6544788b0c14
Revises: eeceafef9f11
Create Date: 2023-06-20 15:27:30.527931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6544788b0c14'
down_revision = 'eeceafef9f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_lend', sa.Column('return_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_lend', 'return_date')
    # ### end Alembic commands ###
