"""empty message

Revision ID: b2d536898be8
Revises: 5e8be65fbce9
Create Date: 2023-06-21 09:47:31.502877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d536898be8'
down_revision = '5e8be65fbce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author_gender', sa.String(length=30), nullable=True))
    op.add_column('book', sa.Column('author_country', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'author_country')
    op.drop_column('book', 'author_gender')
    # ### end Alembic commands ###
